#!/bin/bash

set -ex

# stash, checkout master, rebase
git stash
git checkout master
git fetch
git rebase origin/master

# make a directory to store templates 
mkdir .github
cp -r ../compass-internal-docs/.github/ .github/

# git stuff
git checkout -b pr-templates
git add .
git commit -m "add PR + issue templates"
git push origin pr-templates

# cleanup
git checkout master
git branch -D pr-templates 
