#!/bin/sh
username="lrlna"

get_session () {
  if [ -z "$1"  ]; then
    # tmux 1.9a+ doesn't like .'s in session names
    pwd | sed 's/\./-/g' | awk -F"/" '{print $NF}'
  else
    c "$1"
    echo "$1" | sed 's/\./-/g' | awk -F"/" '{print $NF}'
  fi
}

# check if tmux needs to be booted up
tmux list-sessions | cut -d ':' -f 1 | grep '^_shared$' > /dev/null

# create a new session if there isn't one already
SESSION="$(get_session "$1")"
tmux list-sessions | grep "^$SESSION\:.*$" > /dev/null
if [ "$?" -ne 0  ]; then
  if [ -d "$PROJECTS"/"$SESSION"  ]; then
    cd "$PROJECTS"/"$SESSION" || exit 1
  fi
  tmux new-session -s "$SESSION" -d -n ''
  tmux send-keys "$EDITOR" C-m #':CtrlP' C-m
  tmux split-window -h
  tmux select-window -t "$SESSION"
  tmux select-window -t 1
fi

# attach to session
if [ -z "$TMUX"  ]; then
  tmux attach -t "$SESSION";
else
  tmux switch-client -t "$SESSION"
fi
